package com.example.primerboceto;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.Spinner;

public class registroActivity extends AppCompatActivity {

    private Spinner spinner1;
    private EditText etEmail, etPasswordRegistro, etPasswordRegistroRepe;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_registro);

        etEmail = findViewById(R.id.etEmail);
        etPasswordRegistro = findViewById(R.id.etPasswordRegistro);
        etPasswordRegistroRepe = findViewById(R.id.etPasswordRegistroRepe);
        spinner1 = findViewById(R.id.spinner1);

        String[] opcionesSpinner = {
                "Afganistán",
                "Albania",
                "Alemania",
                "Andorra",
                "Angola",
                "Antigua y Barbuda",
                "Arabia Saudita",
                "Argelia",
                "Argentina",
                "Armenia",
                "Australia",
                "Austria",
                "Azerbaiyán",
                "Bahamas",
                "Bangladés",
                "Barbados",
                "Baréin",
                "Bélgica",
                "Belice",
                "Benín",
                "Bielorrusia",
                "Birmania",
                "Bolivia",
                "Bosnia y Herzegovina",
                "Botsuana",
                "Brasil",
                "Brunéi",
                "Bulgaria",
                "Burkina Faso",
                "Burundi",
                "Bután",
                "Cabo Verde",
                "Camboya",
                "Camerún",
                "Canadá",
                "Catar",
                "Chad",
                "Chile",
                "China",
                "Chipre",
                "Ciudad del Vaticano",
                "Colombia",
                "Comoras",
                "Corea del Norte",
                "Corea del Sur",
                "Costa de Marfil",
                "Costa Rica",
                "Croacia",
                "Cuba",
                "Dinamarca",
                "Dominica",
                "Ecuador",
                "Egipto",
                "El Salvador",
                "Emiratos Árabes Unidos",
                "Eritrea",
                "Eslovaquia",
                "Eslovenia",
                "España",
                "Estados Unidos",
                "Estonia",
                "Etiopía",
                "Filipinas",
                "Finlandia",
                "Fiyi",
                "Francia",
                "Gabón",
                "Gambia",
                "Georgia",
                "Ghana",
                "Granada",
                "Grecia",
                "Guatemala",
                "Guyana",
                "Guinea",
                "Guinea ecuatorial",
                "Guinea-Bisáu",
                "Haití",
                "Honduras",
                "Hungría",
                "India",
                "Indonesia",
                "Irak",
                "Irán",
                "Irlanda",
                "Islandia",
                "Islas Marshall",
                "Islas Salomón",
                "Israel",
                "Italia",
                "Jamaica",
                "Japón",
                "Jordania",
                "Kazajistán",
                "Kenia",
                "Kirguistán",
                "Kiribati",
                "Kuwait",
                "Laos",
                "Lesoto",
                "Letonia",
                "Líbano",
                "Liberia",
                "Libia",
                "Liechtenstein",
                "Lituania",
                "Luxemburgo",
                "Macedonia del Norte",
                "Madagascar",
                "Malasia",
                "Malaui",
                "Maldivas",
                "Malí",
                "Malta",
                "Marruecos",
                "Mauricio",
                "Mauritania",
                "México",
                "Micronesia",
                "Moldavia",
                "Mónaco",
                "Mongolia",
                "Montenegro",
                "Mozambique",
                "Namibia",
                "Nauru",
                "Nepal",
                "Nicaragua",
                "Níger",
                "Nigeria",
                "Noruega",
                "Nueva Zelanda",
                "Omán",
                "Países Bajos",
                "Pakistán",
                "Palaos",
                "Panamá",
                "Papúa Nueva Guinea",
                "Paraguay",
                "Perú",
                "Polonia",
                "Portugal",
                "Reino Unido",
                "República Centroafricana",
                "República Checa",
                "República del Congo",
                "República Democrática del Congo",
                "República Dominicana",
                "Ruanda",
                "Rumanía",
                "Rusia",
                "Samoa",
                "San Cristóbal y Nieves",
                "San Marino",
                "San Vicente y las Granadinas",
                "Santa Lucía",
                "Santo Tomé y Príncipe",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leona",
                "Singapur",
                "Siria",
                "Somalia",
                "Sri Lanka",
                "Suazilandia",
                "Sudáfrica",
                "Sudán",
                "Sudán del Sur",
                "Suecia",
                "Suiza",
                "Surinam",
                "Tailandia",
                "Tanzania",
                "Tayikistán",
                "Timor Oriental",
                "Togo",
                "Tonga",
                "Trinidad y Tobago",
                "Túnez",
                "Turkmenistán",
                "Turquía",
                "Tuvalu",
                "Ucrania",
                "Uganda",
                "Uruguay",
                "Uzbekistán",
                "Vanuatu",
                "Venezuela",
                "Vietnam",
                "Yemen",
                "Yibuti",
                "Zambia",
                "Zimbabue"
        };

        ArrayAdapter <String> adapter = new ArrayAdapter<>(this, android.R.layout.simple_spinner_item, opcionesSpinner);
        spinner1.setAdapter(adapter);
    }

    //Metodo del boton
    public void crearUsu(View v){
        Intent i = new Intent(this, mainActivity.class);
        startActivity(i);
    }
}